Repository sperta-BEmin/BEmin-Server, pull requests merged in 2025-02, with the labels that each got.

#1 Feat: 공통 응답 & global Exception 생성
  build.gradle
  src/main/java/run/bemin/api/general/exception/ErrorCode.java
  src/main/java/run/bemin/api/general/exception/ErrorResponse.java
  src/main/java/run/bemin/api/general/exception/GlobalExceptionHandler.java
  src/main/java/run/bemin/api/general/response/ApiResponse.java
Labels: Feat, Chore

#2 Feat: Security 설정 및 JWT 기반 회원가입 기능 구현
  build.gradle
  src/main/java/run/bemin/api/auth/controller/AuthController.java
  src/main/java/run/bemin/api/auth/jwt/JwtUtil.java
  src/main/java/run/bemin/api/auth/service/AuthService.java
  src/main/java/run/bemin/api/config/WebSecurityConfig.java
  src/main/java/run/bemin/api/general/exception/ErrorCode.java
  src/main/java/run/bemin/api/security/JwtAuthenticationFilter.java
  src/main/java/run/bemin/api/security/JwtAuthorizationFilter.java
  src/main/java/run/bemin/api/security/UserDetailsImpl.java
  src/main/java/run/bemin/api/security/UserDetailsServiceImpl.java
  src/main/java/run/bemin/api/user/controller/UserController.java
  src/main/java/run/bemin/api/user/dto/SignupRequestDto.java
  src/main/java/run/bemin/api/user/dto/SignupResponseDto.java
  src/main/java/run/bemin/api/user/entity/User.java
  src/main/java/run/bemin/api/user/entity/UserRoleEnum.java
  src/main/java/run/bemin/api/user/exception/UserException.java
  src/main/java/run/bemin/api/user/exception/UserExceptionHandler.java
  src/main/java/run/bemin/api/user/repository/UserRepository.java
Labels: Feat, Chore

#4 Fix: 예외 처리 통합 및 UserExceptionHandler 삭제
  src/main/java/run/bemin/api/general/exception/ErrorCode.java
  src/main/java/run/bemin/api/general/exception/GlobalExceptionHandler.java
  src/main/java/run/bemin/api/user/exception/UserExceptionHandler.java
Labels: Fix

#5 Feat: 이메일 중복 확인 기능 구현 및 보안 설정 적용
  src/main/java/run/bemin/api/auth/service/AuthService.java
  src/main/java/run/bemin/api/config/WebSecurityConfig.java
  src/main/java/run/bemin/api/general/exception/ErrorCode.java
  src/main/java/run/bemin/api/user/controller/UserController.java
  src/main/java/run/bemin/api/user/dto/EmailCheckResponseDto.java
  src/main/java/run/bemin/api/user/repository/UserRepository.java
  src/main/java/run/bemin/api/user/service/UserService.java
Labels: Feat

#10 feat: #9 공통 예외에서 카테고리 예외 응답 구현하기
  src/main/java/run/bemin/api/general/exception/ErrorCode.java
Labels: enhancement

#11 카테고리 엔티티/컨트롤러/서비스/리포지토리 구현하기
  build.gradle
  src/main/java/run/bemin/api/auth/controller/AuthController.java
  src/main/java/run/bemin/api/auth/jwt/JwtUtil.java
  src/main/java/run/bemin/api/auth/service/AuthService.java
  src/main/java/run/bemin/api/category/controller/AdminCategoryController.java
  src/main/java/run/bemin/api/category/controller/CategoryController.java
  src/main/java/run/bemin/api/category/dto/CategoryDto.java
  src/main/java/run/bemin/api/category/dto/request/CreateCategoryRequestDto.java
  src/main/java/run/bemin/api/category/entity/Category.java
  src/main/java/run/bemin/api/category/exception/CategoryAlreadyExistsByNameException.java
  src/main/java/run/bemin/api/category/exception/CategoryNameInvalidException.java
  src/main/java/run/bemin/api/category/exception/CategoryNotFoundException.java
  src/main/java/run/bemin/api/category/exception/handler/CategoryExceptionHandler.java
  src/main/java/run/bemin/api/category/exception/validation/CategoryValidationMessages.java
  src/main/java/run/bemin/api/category/repository/CategoryRepository.java
  src/main/java/run/bemin/api/category/service/CategoryService.java
  src/main/java/run/bemin/api/config/WebSecurityConfig.java
  src/main/java/run/bemin/api/general/exception/ErrorCode.java
  src/main/java/run/bemin/api/general/exception/ErrorResponse.java
  src/main/java/run/bemin/api/general/exception/GlobalExceptionHandler.java
  src/main/java/run/bemin/api/general/response/ApiResponse.java
  src/main/java/run/bemin/api/security/JwtAuthenticationFilter.java
  src/main/java/run/bemin/api/security/JwtAuthorizationFilter.java
  src/main/java/run/bemin/api/security/UserDetailsImpl.java
  src/main/java/run/bemin/api/security/UserDetailsServiceImpl.java
  src/main/java/run/bemin/api/user/controller/UserController.java
  src/main/java/run/bemin/api/user/dto/EmailCheckResponseDto.java
  src/main/java/run/bemin/api/user/dto/NicknameCheckResponseDto.java
  src/main/java/run/bemin/api/user/dto/SignupRequestDto.java
  src/main/java/run/bemin/api/user/dto/SignupResponseDto.java
  src/main/java/run/bemin/api/user/entity/User.java
  src/main/java/run/bemin/api/user/entity/UserRoleEnum.java
  src/main/java/run/bemin/api/user/exception/UserException.java
  src/main/java/run/bemin/api/user/repository/UserRepository.java
  src/main/java/run/bemin/api/user/service/UserService.java
Labels: Feat

#21 모든 카테고리 조회 API 구현하기
  src/main/java/run/bemin/BeminApplication.java
  src/main/java/run/bemin/api/category/controller/AdminCategoryController.java
  src/main/java/run/bemin/api/category/controller/CategoryController.java
  src/main/java/run/bemin/api/category/dto/CategoryDto.java
  src/main/java/run/bemin/api/category/dto/CategoryResponseCode.java
  src/main/java/run/bemin/api/category/dto/CategoryValidationMessages.java
  src/main/java/run/bemin/api/category/dto/request/CreateCategoryRequestDto.java
  src/main/java/run/bemin/api/category/entity/Category.java
  src/main/java/run/bemin/api/category/repository/CategoryRepository.java
  src/main/java/run/bemin/api/category/service/CategoryService.java
Labels: Feat

#22 특정 카테고리 수정/삭제 구현하기
  src/main/java/run/bemin/api/category/controller/AdminCategoryController.java
  src/main/java/run/bemin/api/category/dto/CategoryResponseCode.java
  src/main/java/run/bemin/api/category/dto/request/SoftDeleteCategoryRequestDto.java
  src/main/java/run/bemin/api/category/dto/request/UpdateCategoryRequestDto.java
  src/main/java/run/bemin/api/category/entity/Category.java
  src/main/java/run/bemin/api/category/exception/handler/CategoryExceptionHandler.java
  src/main/java/run/bemin/api/category/repository/CategoryRepository.java
  src/main/java/run/bemin/api/category/service/CategoryService.java
Labels: Feat

#23 가게 엔티티 및 등록 API 구현하기
  src/main/java/run/bemin/api/general/exception/ErrorCode.java
  src/main/java/run/bemin/api/store/controller/AdminStoreController.java
  src/main/java/run/bemin/api/store/controller/StoreController.java
  src/main/java/run/bemin/api/store/dto/StoreDto.java
  src/main/java/run/bemin/api/store/dto/StoreResponseCode.java
  src/main/java/run/bemin/api/store/dto/StoreValidationMessages.java
  src/main/java/run/bemin/api/store/dto/request/CreateStoreRequestDto.java
  src/main/java/run/bemin/api/store/entity/Store.java
  src/main/java/run/bemin/api/store/exception/StoreAlreadyExistsByNameException.java
  src/main/java/run/bemin/api/store/exception/StoreNameInvalidException.java
  src/main/java/run/bemin/api/store/exception/StoreNotFoundException.java
  src/main/java/run/bemin/api/store/exception/handler/StoreExceptionHandler.java
  src/main/java/run/bemin/api/store/repository/StoreRepository.java
  src/main/java/run/bemin/api/store/service/StoreService.java
Labels: Feat

#24 가게카테고리 엔티티 구현 및 연관 관계 매핑하기
  src/main/java/run/bemin/api/category/entity/Category.java
  src/main/java/run/bemin/api/store/entity/Store.java
  src/main/java/run/bemin/api/store/entity/StoreCategory.java
Labels: Feat

#25 Feat : Product 및 Auditing 엔티티 추가
  src/main/java/run/bemin/BeminApplication.java
  src/main/java/run/bemin/api/general/auditing/AuditableEntity.java
  src/main/java/run/bemin/api/general/auditing/AuditorAwareImpl.java
  src/main/java/run/bemin/api/general/exception/ErrorCode.java
  src/main/java/run/bemin/api/product/entity/Product.java
  src/main/java/run/bemin/api/product/entity/ProductEntityService.java
  src/main/java/run/bemin/api/product/repository/ProductRepository.java
Labels: Feat

#27 카게주소 엔티티 구현하기
  src/main/java/run/bemin/api/store/entity/Store.java
  src/main/java/run/bemin/api/store/entity/StoreAddress.java
  src/main/java/run/bemin/api/store/entity/StoreCategory.java
Labels: Feat

#29 Feat: 로그인 기능 구현
  src/main/java/run/bemin/api/auth/controller/AuthController.java
  src/main/java/run/bemin/api/auth/dto/SigninRequestDto.java
  src/main/java/run/bemin/api/auth/dto/SigninResponseDto.java
  src/main/java/run/bemin/api/auth/jwt/JwtUtil.java
  src/main/java/run/bemin/api/auth/service/AuthService.java
  src/main/java/run/bemin/api/config/WebSecurityConfig.java
  src/main/java/run/bemin/api/general/exception/ErrorCode.java
  src/main/java/run/bemin/api/general/exception/GlobalExceptionHandler.java
  src/main/java/run/bemin/api/security/JwtAuthenticationFilter.java
  src/main/java/run/bemin/api/security/JwtAuthorizationFilter.java
  src/main/java/run/bemin/api/security/UserDetailsImpl.java
  src/main/java/run/bemin/api/user/service/UserService.java
Labels: Feat, Fix

#30 Fix: WebSecurityConfig 필터 로직 수정
  src/main/java/run/bemin/api/config/WebSecurityConfig.java
Labels: Fix

#33 Feat : Product 도메인 로직 생성
  src/main/java/run/bemin/api/general/exception/ErrorCode.java
  src/main/java/run/bemin/api/product/controller/ProductController.java
  src/main/java/run/bemin/api/product/dto/MessageResponseDto.java
  src/main/java/run/bemin/api/product/dto/ProductRequestDto.java
  src/main/java/run/bemin/api/product/dto/ProductSearchDto.java
  src/main/java/run/bemin/api/product/dto/UpdateProductDetailDto.java
  src/main/java/run/bemin/api/product/entity/Product.java
  src/main/java/run/bemin/api/product/entity/ProductEntityService.java
  src/main/java/run/bemin/api/product/exception/DeletedProductException.java
  src/main/java/run/bemin/api/product/exception/ProductNotFoundException.java
  src/main/java/run/bemin/api/product/exception/UnauthorizedStoreAccessException.java
  src/main/java/run/bemin/api/product/exception/handler/ProductExceptionHandler.java
  src/main/java/run/bemin/api/product/repository/ProductRepository.java
  src/main/java/run/bemin/api/product/service/ProductService.java
  src/main/java/run/bemin/api/product/validator/ProductValidationMessages.java
  src/main/java/run/bemin/api/product/validator/ProductValidator.java
Labels: Feat, Fix, Chore

#34 카테고리 등록 API 권한 검사하기
  src/main/java/run/bemin/api/category/controller/AdminCategoryController.java
  src/main/java/run/bemin/api/category/dto/request/CreateCategoryRequestDto.java
  src/main/java/run/bemin/api/category/service/CategoryService.java
Labels: Feat

#35 Refactor: #32 가게 - 회원 연관 관계 설정 및 권한 확인하기
  src/main/java/run/bemin/api/store/controller/AdminStoreController.java
  src/main/java/run/bemin/api/store/dto/StoreDto.java
  src/main/java/run/bemin/api/store/entity/Store.java
  src/main/java/run/bemin/api/store/entity/StoreAddress.java
  src/main/java/run/bemin/api/store/service/StoreService.java
Labels: Feat

#39 Chore: Product 로직 주석 해제
  src/main/java/run/bemin/api/product/controller/ProductController.java
  src/main/java/run/bemin/api/product/validator/ProductValidator.java
  src/main/java/run/bemin/api/store/repository/StoreRepository.java
Labels: Chore

#40 Feat: 토큰에서 사용자 이메일 추출 기능 구현
  src/main/java/run/bemin/api/auth/jwt/JwtUtil.java
  src/test/java/run/bemin/security/JwtUtilTokenTest.java
Labels: Feat

#41 Refactor: @Order 어노테이션 제거 및 접근 제어자 public 변경
  src/main/java/run/bemin/api/auth/jwt/JwtUtil.java
  src/main/java/run/bemin/api/user/exception/handler/UserExceptionHandler.java
Labels: Chore

#42 Feat: Comment 도메인 생성
  src/main/java/run/bemin/api/comment/entity/Comment.java
  src/main/java/run/bemin/api/comment/repository/CommentRepository.java
Labels: Feat

#43 Feat: 특정 사용자 상세 정보 조회 기능 구현 및 사용자 정보 수정 기능 구현
  src/main/java/run/bemin/api/general/exception/ErrorCode.java
  src/main/java/run/bemin/api/user/controller/UserController.java
  src/main/java/run/bemin/api/user/dto/UserResponseDto.java
  src/main/java/run/bemin/api/user/dto/UserUpdateRequestDto.java
  src/main/java/run/bemin/api/user/entity/User.java
  src/main/java/run/bemin/api/user/exception/UserDuplicateNicknameException.java
  src/main/java/run/bemin/api/user/exception/UserNoFieldUpdatedException.java
  src/main/java/run/bemin/api/user/exception/UserNotFoundException.java
  src/main/java/run/bemin/api/user/exception/handler/UserExceptionHandler.java
  src/main/java/run/bemin/api/user/repository/UserRepository.java
  src/main/java/run/bemin/api/user/service/UserService.java
Labels: Feat

#45 Feat: Comment 도메인 Controller & Service 생성
  build.gradle
  src/main/java/run/bemin/api/comment/config/ChatGPTConfig.java
  src/main/java/run/bemin/api/comment/controller/CommentController.java
  src/main/java/run/bemin/api/comment/dto/CommentDto.java
  src/main/java/run/bemin/api/comment/dto/CommentListDto.java
  src/main/java/run/bemin/api/comment/dto/CommentRequestDto.java
  src/main/java/run/bemin/api/comment/dto/CommentResponseDto.java
  src/main/java/run/bemin/api/comment/dto/GPTRequest.java
  src/main/java/run/bemin/api/comment/dto/GPTResponse.java
  src/main/java/run/bemin/api/comment/dto/Message.java
  src/main/java/run/bemin/api/comment/repository/CommentRepository.java
  src/main/java/run/bemin/api/comment/service/ChatGPTService.java
  src/main/java/run/bemin/api/comment/service/CommentService.java
  src/main/java/run/bemin/api/product/controller/ProductController.java
  src/main/java/run/bemin/api/product/entity/Product.java
  src/main/java/run/bemin/api/product/service/ProductService.java
Labels: Feat, Build

#46 Refactor: #32 감사 기능 수정하기
  src/main/java/run/bemin/BeminApplication.java
  src/main/java/run/bemin/api/config/AuditingConfig.java
  src/main/java/run/bemin/api/general/auditing/AuditableEntity.java
  src/main/java/run/bemin/api/general/auditing/AuditorAwareImpl.java
Labels: Feat

#47 Feat: #32 가게 조회 연관 관계 매핑하기
  src/main/java/run/bemin/api/category/dto/request/CreateCategoryRequestDto.java
  src/main/java/run/bemin/api/category/repository/CategoryRepository.java
  src/main/java/run/bemin/api/store/dto/StoreDto.java
  src/main/java/run/bemin/api/store/dto/StoreValidationMessages.java
  src/main/java/run/bemin/api/store/dto/request/CreateStoreRequestDto.java
  src/main/java/run/bemin/api/store/entity/Store.java
  src/main/java/run/bemin/api/store/entity/StoreAddress.java
  src/main/java/run/bemin/api/store/exception/CategoryCountExceededException.java
  src/main/java/run/bemin/api/store/exception/handler/StoreExceptionHandler.java
  src/main/java/run/bemin/api/store/service/StoreService.java
Labels: Feat

#49 Refactor: #32 필드 update 수정하기
  src/main/java/run/bemin/api/general/auditing/AuditableEntity.java
Labels: Feat

#52 Refactor: #51 회원가입을 고려한 Audit 수정하기
  src/main/java/run/bemin/api/general/auditing/AuditorAwareImpl.java
  src/main/java/run/bemin/api/user/entity/User.java
Labels: Feat

#55 가게 수정 API 구현 및 가게, 카테고리 audit 적용하기
  src/main/java/run/bemin/api/category/controller/AdminCategoryController.java
  src/main/java/run/bemin/api/category/controller/CategoryController.java
  src/main/java/run/bemin/api/category/entity/Category.java
  src/main/java/run/bemin/api/store/controller/AdminStoreController.java
  src/main/java/run/bemin/api/store/dto/StoreDto.java
  src/main/java/run/bemin/api/store/dto/request/UpdateAllStoreRequestDto.java
  src/main/java/run/bemin/api/store/entity/Store.java
  src/main/java/run/bemin/api/store/entity/StoreAddress.java
  src/main/java/run/bemin/api/store/entity/StoreCategory.java
  src/main/java/run/bemin/api/store/service/StoreService.java
Labels: Feat

#56 Refactor: #31 카테고리 API 권한 적용하기
  src/main/java/run/bemin/api/category/controller/AdminCategoryController.java
  src/main/java/run/bemin/api/category/controller/CategoryController.java
Labels: Feat

#57 카테고리 API 수정하기
  src/main/java/run/bemin/api/category/dto/CategoryValidationMessages.java
  src/main/java/run/bemin/api/category/dto/request/SoftDeleteCategoryRequestDto.java
  src/main/java/run/bemin/api/category/dto/request/UpdateCategoryRequestDto.java
  src/main/java/run/bemin/api/category/service/CategoryService.java
Labels: Feat

#63 Fix: product controller 요청 URL 수정
  src/main/java/run/bemin/api/product/controller/ProductController.java
Labels: Fix

#65 Fix: #64 가게 예외 응답 구현하기
  src/main/java/run/bemin/api/general/exception/ErrorCode.java
Labels: Feat

#70 카테고리 API 최적화하기
  src/main/java/run/bemin/api/category/controller/AdminCategoryController.java
  src/main/java/run/bemin/api/category/controller/CategoryController.java
  src/main/java/run/bemin/api/category/dto/response/GetCategoryResponseDto.java
  src/main/java/run/bemin/api/category/repository/CategoryRepository.java
  src/main/java/run/bemin/api/category/service/CategoryService.java
Labels: Feat

#73 Feat: 로그아웃 기능 구현 (JWT 기반)
  src/main/java/run/bemin/api/auth/controller/AuthController.java
  src/main/java/run/bemin/api/auth/dto/SigninResponseDto.java
  src/main/java/run/bemin/api/auth/dto/SignoutResponseDto.java
  src/main/java/run/bemin/api/auth/service/AuthService.java
Labels: Feat

#74 가게 조회 페이징 구현 및 최적화하기
  src/main/java/run/bemin/api/category/controller/AdminCategoryController.java
  src/main/java/run/bemin/api/category/service/CategoryService.java
  src/main/java/run/bemin/api/product/validator/ProductValidator.java
  src/main/java/run/bemin/api/store/controller/AdminStoreController.java
  src/main/java/run/bemin/api/store/controller/StoreController.java
  src/main/java/run/bemin/api/store/dto/StoreDto.java
  src/main/java/run/bemin/api/store/dto/request/CreateStoreRequestDto.java
  src/main/java/run/bemin/api/store/dto/response/AdminStoreResponseDto.java
  src/main/java/run/bemin/api/store/dto/response/GetStoreResponseDto.java
  src/main/java/run/bemin/api/store/entity/Store.java
  src/main/java/run/bemin/api/store/entity/StoreCategory.java
  src/main/java/run/bemin/api/store/repository/StoreRepository.java
  src/main/java/run/bemin/api/store/service/StoreService.java
  src/main/java/run/bemin/api/user/entity/User.java
Labels: Feat

#77 Refactor: 전체 회원 조회 시 생성일 기준 정렬 기능 추가
  src/main/java/run/bemin/api/user/service/UserService.java
Labels: Feat

#78 Refactor: 전체 회원 조회 시 생성일 기준 정렬 기능 추가
  src/main/java/run/bemin/api/user/controller/UserController.java
Labels: Feat

#81 가게 수정 API 추가 구현하기
  src/main/java/run/bemin/api/store/controller/AdminStoreController.java
  src/main/java/run/bemin/api/store/dto/StoreDto.java
  src/main/java/run/bemin/api/store/dto/request/StoreActivationStatusDto.java
  src/main/java/run/bemin/api/store/dto/request/UpdateAddressInStoreRequestDto.java
  src/main/java/run/bemin/api/store/dto/request/UpdateCategoriesInStoreRequestDto.java
  src/main/java/run/bemin/api/store/dto/request/UpdateStoreActivationRequestDto.java
  src/main/java/run/bemin/api/store/dto/request/UpdateStoreOwnerRequestDto.java
  src/main/java/run/bemin/api/store/dto/request/UpdateStorePhoneRequestDto.java
  src/main/java/run/bemin/api/store/dto/request/UpdateStoresActivationStatusRequestDto.java
  src/main/java/run/bemin/api/store/dto/response/UpdateCategoriesInStoreResponseDto.java
  src/main/java/run/bemin/api/store/entity/Store.java
  src/main/java/run/bemin/api/store/service/StoreService.java
Labels: Feat

#83 3. QueryDSL 구현하기
  build.gradle
  src/main/java/run/bemin/api/store/controller/StoreController.java
  src/main/java/run/bemin/api/store/dto/StoreSimpleDto.java
  src/main/java/run/bemin/api/store/repository/StoreRepository.java
  src/main/java/run/bemin/api/store/repository/StoreRepositoryCustom.java
  src/main/java/run/bemin/api/store/repository/StoreRepositoryImpl.java
  src/main/java/run/bemin/api/store/service/StoreService.java
  src/main/java/run/bemin/api/user/entity/User.java
Labels: Feat

#86 Feat: User와 UserAddress 소프트 삭제 및 Auditing 적용
  src/main/java/run/bemin/api/user/controller/UserController.java
  src/main/java/run/bemin/api/user/entity/User.java
  src/main/java/run/bemin/api/user/entity/UserAddress.java
  src/main/java/run/bemin/api/user/service/UserService.java
Labels: Feat

#88 이메일로 단 건 가게 목록 조회 API 수정하기
  src/main/java/run/bemin/api/store/controller/AdminStoreController.java
Labels: Fix

#92 Feat: 회원 및 주소 관리 API 개선
  src/main/java/run/bemin/api/user/controller/UserController.java
  src/main/java/run/bemin/api/user/dto/UserAddressResponseDto.java
  src/main/java/run/bemin/api/user/dto/UserResponseDto.java
  src/main/java/run/bemin/api/user/repository/UserAddressRepository.java
  src/main/java/run/bemin/api/user/repository/UserRepository.java
  src/main/java/run/bemin/api/user/service/UserAddressService.java
  src/main/java/run/bemin/api/user/service/UserService.java
Labels: Feat

#93 Feat: 이미지 최적화 및 S3 연동
  build.gradle
  src/main/java/run/bemin/api/general/exception/ErrorCode.java
  src/main/java/run/bemin/api/image/FoodImg.java
  src/main/java/run/bemin/api/image/S3/controller/S3Controller.java
  src/main/java/run/bemin/api/image/S3/service/S3Service.java
  src/main/java/run/bemin/api/image/exception/S3InvalidFormatException.java
  src/main/java/run/bemin/api/image/exception/S3UploadFailException.java
  src/main/java/run/bemin/api/image/exception/handler/S3ExceptionHandler.java
  src/main/java/run/bemin/api/image/util/PixelUtil.java
  src/main/java/run/bemin/api/image/util/UrlUtil.java
  src/main/java/run/bemin/api/product/controller/ProductController.java
  src/main/java/run/bemin/api/product/service/ProductService.java
  src/main/java/run/bemin/api/store/exception/StoreNotFoundException.java
Labels: Feat, Fix, Chore

#96 Fix: #95 회원 이메일로 가게 조회 API 수정하기
  src/main/java/run/bemin/api/store/service/StoreService.java
Labels: Fix

#97 Fix: User - UserAddress 엔티티간 순환 참조 및 lazy 프록시 직렬화 오류 해결
  build.gradle
  src/main/java/run/bemin/api/config/JacksonConfig.java
  src/main/java/run/bemin/api/user/entity/User.java
  src/main/java/run/bemin/api/user/entity/UserAddress.java
Labels: Fix

#99 요구사항 명세서 반영 및 이메일로 가게 조회 API 수정 완료
  http-requests/category.http
  http-requests/store.http
  http-requests/user.http
  src/main/java/run/bemin/api/category/controller/AdminCategoryController.java
  src/main/java/run/bemin/api/category/controller/CategoryController.java
  src/main/java/run/bemin/api/category/dto/request/UpdateCategoryRequestDto.java
  src/main/java/run/bemin/api/category/dto/request/UpdateMinimumPriceRequestDto.java
  src/main/java/run/bemin/api/category/dto/request/UpdateStoreNameRequestDto.java
  src/main/java/run/bemin/api/category/service/CategoryService.java
  src/main/java/run/bemin/api/store/controller/AdminStoreController.java
  src/main/java/run/bemin/api/store/controller/StoreController.java
  src/main/java/run/bemin/api/store/dto/StoreDto.java
  src/main/java/run/bemin/api/store/dto/StoreSimpleDto.java
  src/main/java/run/bemin/api/store/dto/request/CreateStoreRequestDto.java
  src/main/java/run/bemin/api/store/entity/Store.java
  src/main/java/run/bemin/api/store/service/StoreService.java
Labels: Feat

#101 🎉🎉🎉[#100돌파] API 명세서 최신화에 따른 수정 사항 반영하기 🎉🎉🎉
  src/main/java/run/bemin/api/store/dto/StoreDto.java
  src/main/java/run/bemin/api/store/dto/request/UpdateAllStoreRequestDto.java
  src/main/java/run/bemin/api/store/repository/StoreRepositoryImpl.java
Labels: Fix

#103 Fix: #102 가게 검색 로직 수정하기
  src/main/java/run/bemin/api/store/repository/StoreRepositoryImpl.java
Labels: Fix

#104 Fix: @Param 추가
  src/main/java/run/bemin/api/product/repository/ProductRepository.java
Labels: Fix

#105 Fix: boolean 기본값 설정 방법 수정
  src/main/java/run/bemin/api/product/entity/Product.java
Labels: Fix

#106 Feature: Auth 도메인 테스트 구현
  src/main/java/run/bemin/api/auth/controller/AuthSessionController.java
  src/main/java/run/bemin/api/auth/controller/AuthSignupController.java
  src/main/java/run/bemin/api/auth/dto/SigninRequestDto.java
  src/main/java/run/bemin/api/auth/exception/handler/AuthExceptionHandler.java
  src/main/java/run/bemin/api/auth/exception/handler/SigninExceptionHandler.java
  src/main/java/run/bemin/api/auth/exception/handler/SignupExceptionHandler.java
  src/main/java/run/bemin/api/auth/service/AuthService.java
  src/main/java/run/bemin/api/config/WebSecurityConfig.java
  src/main/java/run/bemin/api/general/exception/ErrorCode.java
  src/main/java/run/bemin/api/user/exception/handler/UserExceptionHandler.java
  src/test/java/run/bemin/api/auth/controller/AuthSessionControllerTest.java
  src/test/java/run/bemin/api/auth/controller/AuthSignupControllerTest.java
  src/test/java/run/bemin/api/auth/service/AuthServiceTest.java
  src/test/java/run/bemin/api/config/MockConfig.java
  src/test/java/run/bemin/api/config/TestSecurityConfig.java
  src/test/java/run/bemin/security/JwtUtilTokenTest.java
Labels: Feat

#112 Fix: 상품 조회 API 수정
  src/main/java/run/bemin/api/product/dto/ProductSearchDto.java
  src/main/java/run/bemin/api/product/repository/ProductRepository.java
Labels: Fix

#115 가게 등록 API 수정하기
  src/main/java/run/bemin/api/store/dto/request/CreateStoreRequestDto.java
  src/main/java/run/bemin/api/store/entity/Store.java
  src/main/java/run/bemin/api/store/service/StoreService.java
Labels: Fix

#116 카테고리 테스트 케이스 구현하기
  src/test/java/run/bemin/api/category/service/CategoryServiceTest.java
Labels: Feat

#119 Feat: Swagger 적용
  build.gradle
  src/main/java/run/bemin/api/config/SwaggerConfig.java
  src/main/java/run/bemin/api/config/WebSecurityConfig.java
  src/main/java/run/bemin/api/product/controller/ProductController.java
  src/main/java/run/bemin/api/product/dto/ProductRequestDto.java
  src/main/java/run/bemin/api/security/JwtAuthorizationFilter.java
Labels: Feat, Build

#125 Refactor: Auth 도메인 컨트롤러, DTO 및 폴더 구조 최적화
  src/main/java/run/bemin/api/auth/controller/SessionController.java
  src/main/java/run/bemin/api/auth/controller/SignupController.java
  src/main/java/run/bemin/api/auth/dto/TokenDto.java
  src/main/java/run/bemin/api/auth/dto/request/SigninRequestDto.java
  src/main/java/run/bemin/api/auth/dto/request/SignupRequestDto.java
  src/main/java/run/bemin/api/auth/dto/response/EmailCheckResponseDto.java
  src/main/java/run/bemin/api/auth/dto/response/NicknameCheckResponseDto.java
  src/main/java/run/bemin/api/auth/dto/response/RefreshResponseDto.java
  src/main/java/run/bemin/api/auth/dto/response/SigninResponseDto.java
  src/main/java/run/bemin/api/auth/dto/response/SignoutResponseDto.java
  src/main/java/run/bemin/api/auth/dto/response/SignupResponseDto.java
  src/main/java/run/bemin/api/auth/exception/handler/SigninExceptionHandler.java
  src/main/java/run/bemin/api/auth/service/AuthService.java
  src/main/java/run/bemin/api/auth/util/CookieUtil.java
  src/main/java/run/bemin/api/auth/util/JwtUtil.java
  src/main/java/run/bemin/api/auth/util/ResponseBuilder.java
  src/main/java/run/bemin/api/config/WebSecurityConfig.java
  src/main/java/run/bemin/api/review/service/ReviewService.java
  src/main/java/run/bemin/api/security/JwtAuthorizationFilter.java
  src/test/java/run/bemin/api/auth/controller/SessionControllerTest.java
  src/test/java/run/bemin/api/auth/controller/SignupControllerTest.java
  src/test/java/run/bemin/api/auth/service/AuthServiceTest.java
  src/test/java/run/bemin/api/config/MockConfig.java
Labels: Fix

#127 Docs : Product와 Comment 도메인 Swagger & JavaDocs 문서화 추가
  src/main/java/run/bemin/api/comment/controller/CommentController.java
  src/main/java/run/bemin/api/image/S3/controller/S3Controller.java
  src/main/java/run/bemin/api/product/controller/ProductController.java
Labels: Docs

#129 [RabbitMQ, Redis] 가게 평점 통합 테스트 구현하기
  src/main/java/run/bemin/api/category/entity/Category.java
  src/main/java/run/bemin/api/category/service/CategoryService.java
  src/main/java/run/bemin/api/review/dto/ReviewCreateRequestDto.java
  src/main/java/run/bemin/api/review/dto/ReviewCreateResponseDto.java
  src/main/java/run/bemin/api/review/entity/Review.java
  src/main/java/run/bemin/api/review/service/ReviewService.java
  src/main/java/run/bemin/api/store/repository/StoreRepository.java
  src/test/java/run/bemin/api/category/service/CategoryServiceTest.java
  src/test/java/run/bemin/api/review/ReviewIntegrationTest.java
Labels: Feat

#130 Fix: 통합 테스트 Disabled 수정하기
  src/test/java/run/bemin/api/review/ReviewIntegrationTest.java
Labels: Fix

#134 Docs : Auth와 User 도메인 Swagger & JavaDocs 문서화 추가
  src/main/java/run/bemin/api/auth/controller/SessionController.java
  src/main/java/run/bemin/api/auth/controller/SignupController.java
  src/main/java/run/bemin/api/user/controller/UserController.java
Labels: Docs

#137 가게, 카테고리 Swagger, JavaDoc 작성하기
  src/main/java/run/bemin/api/category/controller/AdminCategoryController.java
  src/main/java/run/bemin/api/category/controller/CategoryController.java
  src/main/java/run/bemin/api/store/controller/AdminStoreController.java
  src/main/java/run/bemin/api/store/controller/StoreController.java
Labels: Feat

#136 Docs: 태그 description 수정
  src/main/java/run/bemin/api/auth/controller/SessionController.java
  src/main/java/run/bemin/api/auth/controller/SignupController.java
  src/main/java/run/bemin/api/user/controller/UserController.java
Labels: Fix, Docs

#138 가게, 카테고리 스웨거 공백 추가하기
  src/main/java/run/bemin/api/category/controller/AdminCategoryController.java
  src/main/java/run/bemin/api/category/controller/CategoryController.java
  src/main/java/run/bemin/api/store/controller/AdminStoreController.java
  src/main/java/run/bemin/api/store/controller/StoreController.java
Labels: Fix

#139 Fix: 액세스 토큰, 리프레시 토큰 만료시간 변경
  src/main/java/run/bemin/api/auth/util/JwtUtil.java
Labels: Fix

#143 Feat: #142 리드미 파일 생성하기
  README.md
Labels: Docs

#145 Feat: #142 리드미 파일 역할 추가하기
  README.md
Labels: Docs

#146 Feat: #142 리드미 블로그 추가하기
  README.md
Labels: Docs

#148 Feat: #147 1만 개 리뷰 생성 테스트 구현하기
  src/test/java/run/bemin/api/review/ReviewIntegrationTest.java
Labels: Feat
